import json
import os
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

class Exporter:
    @staticmethod
    def generate_jupyter_notebook(workflow, dataset_name: str, target_col: str) -> str:
        nb = new_notebook()
        
        # 1. Header
        nb.cells.append(new_markdown_cell(f"# AWIP AI-Generated Pipeline\n\n**Dataset**: `{dataset_name}`\n\nThis notebook contains the complete, reproducible pipeline generated by AWIP's AI agents."))
        
        # 2. Imports
        imports = (
            "import pandas as pd\n"
            "import numpy as np\n"
            "from sklearn.pipeline import Pipeline\n"
            "from sklearn.model_selection import train_test_split\n"
        )
        for s in workflow.steps:
            if s.name == "IterativeImputer":
                imports += "from sklearn.experimental import enable_iterative_imputer\nfrom sklearn.impute import IterativeImputer\n"
            elif s.name == "KNNImputer":
                imports += "from sklearn.impute import KNNImputer\n"
            elif s.name == "TargetEncoder":
                imports += "from sklearn.preprocessing import TargetEncoder\n"
            elif s.name == "OrdinalEncoder":
                imports += "from sklearn.preprocessing import OrdinalEncoder\n"
            elif s.name == "RobustScaler":
                imports += "from sklearn.preprocessing import RobustScaler\n"
            elif s.name == "StandardScaler":
                imports += "from sklearn.preprocessing import StandardScaler\n"
            elif s.name == "SMOTE":
                imports += "from imblearn.over_sampling import SMOTE\n"
            elif s.name == "SMOTE + Tomek":
                imports += "from imblearn.combine import SMOTETomek\n"
            elif s.name == "PCA":
                imports += "from sklearn.decomposition import PCA\n"
            elif s.name == "XGBoost":
                imports += "from xgboost import XGBClassifier\n"
            elif s.name == "XGBoost Regressor":
                imports += "from xgboost import XGBRegressor\n"
            elif s.name == "LightGBM":
                imports += "from lightgbm import LGBMClassifier\n"
            elif s.name == "RandomForest":
                imports += "from sklearn.ensemble import RandomForestClassifier\n"
            elif s.name == "LogisticRegression":
                imports += "from sklearn.linear_model import LogisticRegression\n"
                
        nb.cells.append(new_code_cell(imports))
        
        # 3. Load Data
        nb.cells.append(new_markdown_cell("## 1. Load Data\nUpdate the path to your dataset below if needed."))
        nb.cells.append(new_code_cell(f"df = pd.read_csv('{dataset_name}')\n\nTARGET_COL = '{target_col}'\nX = df.drop(columns=[TARGET_COL])\ny = df[TARGET_COL]\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nprint(f'Training shape: {{X_train.shape}}')"))
        
        # 4. Pipeline Construction
        nb.cells.append(new_markdown_cell("## 2. Define Pipeline\nThis pipeline was adapted dynamically based on the dataset's statistical properties."))
        
        pipeline_code = "steps = [\n"
        for s in workflow.steps:
            if s.category in ("explainability", "evaluation", "load_dataset", "generate_report"):
                continue
                
            args = []
            for k, v in s.params.items():
                if isinstance(v, str) and v not in ["balanced", "auto", "use_encoded_value"]:
                    args.append(f"{k}='{v}'")
                elif isinstance(v, str) and v in ["balanced", "auto", "use_encoded_value"]:
                    args.append(f"{k}='{v}'")
                else:
                    args.append(f"{k}={v}")
            arg_str = ", ".join(args)
            
            model_class = s.name
            if model_class == "XGBoost": model_class = "XGBClassifier"
            if model_class == "XGBoost Regressor": model_class = "XGBRegressor"
            if model_class == "LightGBM": model_class = "LGBMClassifier"
            if model_class == "RandomForest": model_class = "RandomForestClassifier"
            if model_class == "SMOTE + Tomek": model_class = "SMOTETomek"
            
            pipeline_code += f"    ('{s.id}', {model_class}({arg_str})),\n"
            
        pipeline_code += "]\n\npipeline = Pipeline(steps)\npipeline"
        nb.cells.append(new_code_cell(pipeline_code))
        
        # 5. Train & Predict
        nb.cells.append(new_markdown_cell("## 3. Train & Evaluate"))
        nb.cells.append(new_code_cell("pipeline.fit(X_train, y_train)\npredictions = pipeline.predict(X_test)\n\nfrom sklearn.metrics import classification_report, accuracy_score\nif len(np.unique(y)) <= 10:\n    print(f'Accuracy: {accuracy_score(y_test, predictions):.4f}')\n    print('\\nClassification Report:')\n    print(classification_report(y_test, predictions))"))
        
        return nbformat.writes(nb)
        
    @staticmethod
    def generate_fastapi_app(workflow) -> str:
        code = (
            "from fastapi import FastAPI\n"
            "from pydantic import BaseModel\n"
            "import joblib\n"
            "import pandas as pd\n\n"
            "app = FastAPI(title='AWIP Model Server')\n\n"
            "# Load the trained pipeline\n"
            "try:\n"
            "    pipeline = joblib.load('pipeline.pkl')\n"
            "except Exception:\n"
            "    pipeline = None\n"
            "    print('Warning: pipeline.pkl not found. Please train and save the model first.')\n\n"
            "class PredictRequest(BaseModel):\n"
            "    features: dict\n\n"
            "@app.get('/health')\n"
            "def health_check():\n"
            "    return {'status': 'healthy', 'model_loaded': pipeline is not None}\n\n"
            "@app.post('/predict')\n"
            "def predict(req: PredictRequest):\n"
            "    if not pipeline:\n"
            "        return {'error': 'Model not loaded'}\n"
            "    \n"
            "    df = pd.DataFrame([req.features])\n"
            "    pred = pipeline.predict(df)\n"
            "    \n"
            "    # If it supports proba\n"
            "    if hasattr(pipeline, 'predict_proba'):\n"
            "        proba = pipeline.predict_proba(df)[0].tolist()\n"
            "        return {'prediction': pred[0].item(), 'probabilities': proba}\n"
            "    \n"
            "    return {'prediction': pred[0].item()}\n"
        )
        return code
        
    @staticmethod
    def generate_dockerfile() -> str:
        return (
            "FROM python:3.10-slim\n\n"
            "WORKDIR /app\n\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n\n"
            "COPY app.py .\n"
            "COPY pipeline.pkl ./\n\n"
            "EXPOSE 8000\n\n"
            "CMD [\"uvicorn\", \"app:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n"
        )
        
    @staticmethod
    def generate_requirements() -> str:
        return (
            "fastapi==0.110.0\n"
            "uvicorn==0.27.1\n"
            "pandas==2.2.0\n"
            "scikit-learn==1.4.0\n"
            "xgboost==2.0.3\n"
            "lightgbm==4.3.0\n"
            "joblib==1.3.2\n"
        )
