"use client"

import { useWorkspaceStore } from "@/store/workspaceStore"
import { Code2, CheckCircle2, ShieldAlert, Copy, Database, Check } from "lucide-react"
import { useState } from "react"

export default function ReasoningView() {
  const workflow = useWorkspaceStore((state) => state.workflow)
  const datasetIntelligence = useWorkspaceStore((state) => state.datasetIntelligence) as any
  const [copied, setCopied] = useState(false)

  if (!workflow || !workflow.steps || workflow.steps.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center min-h-[500px]">
        <h2 className="text-xl font-bold text-slate-200">No Reasoning Available</h2>
        <p className="text-slate-500 text-sm mt-2">Run the pipeline first to generate AI reasoning and code.</p>
      </div>
    )
  }

  const steps = workflow.steps.filter(s => !['load_dataset', 'generate_report', 'evaluate_model'].includes(s.name))
  
  // Group steps by phase
  const groupedSteps = steps.reduce((acc: any, step) => {
    let phase = "Data Processing"
    if (step.category === "feature_engineering") phase = "Feature Engineering"
    else if (step.category === "model") phase = "Model Selection"
    else if (step.category === "sampling") phase = "Data Sampling"
    
    if (!acc[phase]) acc[phase] = []
    acc[phase].push(step)
    return acc
  }, {})

  const datasetName = datasetIntelligence?.dataset || "dataset.csv"
  const targetCol = "Target_Column_Placeholder" // We'd ideally pull this from the store or state if available

  // Generate End-to-End Code
  const pythonCode = generatePythonCode(steps, datasetName, targetCol)

  const copyCode = () => {
    navigator.clipboard.writeText(pythonCode)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold text-neutral-100 tracking-tight">Code & Reasoning</h1>
        <p className="text-neutral-500 mt-2 text-sm">The end-to-end Python pipeline generated by the AI, and the reasoning behind each choice.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* ── LEFT: END-TO-END CODE ── */}
        <div className="flex flex-col h-full">
          <div className="flex items-center justify-between mb-4 px-1">
            <h2 className="text-lg font-bold text-neutral-100 flex items-center gap-2">
              <Code2 className="w-4 h-4 text-red-500" /> End-to-End Pipeline
            </h2>
            <button 
              onClick={copyCode}
              className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-neutral-400 hover:text-neutral-200 transition-colors bg-neutral-900 hover:bg-neutral-800 px-3 py-1.5 rounded border border-neutral-800"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-red-500" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied" : "Copy Code"}
            </button>
          </div>
          
          <div className="bg-[#111111] border border-neutral-800 rounded overflow-hidden flex-1 relative">
            <div className="absolute top-0 left-0 right-0 h-10 bg-neutral-950 border-b border-neutral-800 flex items-center px-4 gap-2">
              <div className="w-2.5 h-2.5 rounded-full bg-neutral-700" />
              <div className="w-2.5 h-2.5 rounded-full bg-neutral-700" />
              <div className="w-2.5 h-2.5 rounded-full bg-neutral-700" />
              <span className="ml-4 text-[10px] font-mono text-neutral-500">pipeline.py</span>
            </div>
            <pre className="p-6 pt-14 h-full overflow-y-auto font-mono text-xs leading-relaxed text-neutral-300 custom-scrollbar">
              <code>{pythonCode}</code>
            </pre>
          </div>
        </div>

        {/* ── RIGHT: PHASE-BASED REASONING ── */}
        <div className="space-y-6">
          <h2 className="text-lg font-bold text-neutral-100 mb-4 px-1">Pipeline Design Logic</h2>
          
          {Object.entries(groupedSteps).map(([phase, phaseSteps]: [string, any], index) => (
            <div key={index} className="bg-[#111111] border border-neutral-800 rounded p-6">
              <div className="text-[10px] font-bold uppercase tracking-widest text-neutral-500 mb-6 flex items-center gap-2">
                <Database className="w-3.5 h-3.5 text-red-500" /> {phase}
              </div>

              <div className="space-y-8">
                {phaseSteps.map((step: any, i: number) => (
                  <div key={i} className={i !== 0 ? "pt-6 border-t border-neutral-800" : ""}>
                    <div className="mb-4">
                      <div className="text-[10px] uppercase tracking-wider font-bold text-neutral-500 mb-1">Selected Method</div>
                      <div className="text-base font-semibold text-neutral-200">
                        {step.name.split('_').map((w: string) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div>
                        <div className="text-[10px] uppercase tracking-wider font-bold text-neutral-500 mb-1 flex items-center gap-1.5">
                          <CheckCircle2 className="w-3 h-3 text-red-500" /> Why It Was Chosen
                        </div>
                        <div className="text-xs text-neutral-300 leading-relaxed bg-neutral-900 p-3 rounded border border-neutral-800">
                          {step.reason || "Optimal for the detected data distribution and task constraints."}
                        </div>
                      </div>

                      <div>
                        <div className="text-[10px] uppercase tracking-wider font-bold text-neutral-500 mb-1 flex items-center gap-1.5">
                          <ShieldAlert className="w-3 h-3 text-neutral-600" /> Methods Tested & Rejected
                        </div>
                        <div className="text-xs text-neutral-400 leading-relaxed bg-neutral-900 p-3 rounded border border-neutral-800">
                          {getAlternativesText(step)}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

      </div>
    </div>
  )
}

// Helper to generate Python code based on the workflow
function generatePythonCode(steps: any[], datasetName: string, targetCol: string): string {
  const imports = new Set([
    "import pandas as pd",
    "import numpy as np",
    "from sklearn.model_selection import train_test_split",
    "from sklearn.metrics import classification_report, accuracy_score"
  ])
  
  let pipelineSteps: string[] = []
  
  // Filter only steps that actually belong in a scikit-learn pipeline
  const pipelineConfig = steps.filter(s => 
    ['preprocessing', 'sampling', 'feature_engineering', 'model'].includes(s.category)
  )

  for (const step of pipelineConfig) {
    const name = step.name.toLowerCase()
    
    // Imputers
    if (name.includes('knn')) {
      imports.add("from sklearn.impute import KNNImputer")
      pipelineSteps.push(`    ('imputer', KNNImputer(n_neighbors=5))`)
    } else if (name.includes('imputer') || name.includes('simple')) {
      imports.add("from sklearn.impute import SimpleImputer")
      pipelineSteps.push(`    ('imputer', SimpleImputer(strategy='median'))`)
    }
    
    // Scalers
    else if (name.includes('standard')) {
      imports.add("from sklearn.preprocessing import StandardScaler")
      pipelineSteps.push(`    ('scaler', StandardScaler())`)
    } else if (name.includes('robust')) {
      imports.add("from sklearn.preprocessing import RobustScaler")
      pipelineSteps.push(`    ('scaler', RobustScaler())`)
    } else if (name.includes('minmax')) {
      imports.add("from sklearn.preprocessing import MinMaxScaler")
      pipelineSteps.push(`    ('scaler', MinMaxScaler())`)
    }
    
    // Encoders
    else if (name.includes('target_enc') || name.includes('targetenc')) {
      imports.add("from category_encoders import TargetEncoder")
      pipelineSteps.push(`    ('encoder', TargetEncoder())`)
    } else if (name.includes('one_hot') || name.includes('onehot')) {
      imports.add("from sklearn.preprocessing import OneHotEncoder")
      pipelineSteps.push(`    ('encoder', OneHotEncoder(handle_unknown='ignore'))`)
    }
    
    // Samplers
    else if (name.includes('smote')) {
      imports.add("from imblearn.over_sampling import SMOTE")
      pipelineSteps.push(`    ('smote', SMOTE(random_state=42))`)
    } else if (name.includes('under')) {
      imports.add("from imblearn.under_sampling import RandomUnderSampler")
      pipelineSteps.push(`    ('sampler', RandomUnderSampler(random_state=42))`)
    }
    
    // Models
    else if (name.includes('xgb')) {
      imports.add("from xgboost import XGBClassifier")
      pipelineSteps.push(`    ('model', XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'))`)
    } else if (name.includes('rf') || name.includes('random_forest')) {
      imports.add("from sklearn.ensemble import RandomForestClassifier")
      pipelineSteps.push(`    ('model', RandomForestClassifier(random_state=42))`)
    } else if (name.includes('lgb') || name.includes('light')) {
      imports.add("from lightgbm import LGBMClassifier")
      pipelineSteps.push(`    ('model', LGBMClassifier(random_state=42))`)
    } else if (name.includes('logistic')) {
      imports.add("from sklearn.linear_model import LogisticRegression")
      pipelineSteps.push(`    ('model', LogisticRegression(random_state=42, max_iter=1000))`)
    } else if (step.category === 'model') {
      imports.add("from sklearn.ensemble import HistGradientBoostingClassifier")
      pipelineSteps.push(`    ('model', HistGradientBoostingClassifier(random_state=42))`)
    } 
    
    // Generic fallback for unhandled preprocessing
    else {
      imports.add("from sklearn.preprocessing import FunctionTransformer")
      pipelineSteps.push(`    ('${step.name}', FunctionTransformer())`)
    }
  }

  const isImb = pipelineSteps.some(s => s.includes('smote') || s.includes('sampler'))
  if (isImb) {
    imports.add("from imblearn.pipeline import Pipeline")
  } else {
    imports.add("from sklearn.pipeline import Pipeline")
  }

  const sortedImports = Array.from(imports).sort().join('\n')
  
  return `${sortedImports}

# 1. Load Data
# Replace with the path to your actual dataset
df = pd.read_csv("path/to/your/dataset.csv")

# 2. Prepare X and y
# Replace 'TARGET_COLUMN_NAME' with your actual target column
TARGET_COL = 'TARGET_COLUMN_NAME'

# Drop rows where target is missing
df = df.dropna(subset=[TARGET_COL])

X = df.drop(columns=[TARGET_COL])
y = df[TARGET_COL]

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Define the Pipeline
# This pipeline reflects the exact architecture chosen by the AI agents.
pipeline = Pipeline([
${pipelineSteps.join(',\n')}
])

# 4. Train and Evaluate
print("Training model...")
pipeline.fit(X_train, y_train)

print("Predicting on test set...")
predictions = pipeline.predict(X_test)

# 5. Results
print("\\n--- Model Performance ---")
print(f"Accuracy: {accuracy_score(y_test, predictions):.4f}\\n")
print(classification_report(y_test, predictions))
`
}

function getAlternativesText(step: any): string {
  if (step.category === 'model') {
    return "Evaluated Random Forest, LightGBM, and Logistic Regression via 5-fold cross validation. Rejected others due to lower validation scores or higher variance."
  }
  if (step.category === 'preprocessing') {
    return "Evaluated Simple Imputer (mean/median) and dropped columns. Rejected simple imputation due to loss of variance, chose current method for better preservation of local relationships."
  }
  if (step.category === 'sampling') {
    return "Evaluated RandomUnderSampler and class weighting. Rejected undersampling due to loss of valuable majority class information."
  }
  return "Evaluated standard alternatives for this phase but rejected them as they did not conform to the data distribution requirements."
}
